### ISSUE TITLE
babel/es6

### ISSUE THREAD

**Issue by dozoisch** [dozoisch/koa-react-full-example#21]

**Comment by thejameskyle** [comment]
Hey @dozoisch, Babel contributor here. If you need any help getting Babel setup let me know or ask in our support chat: https://gitter.im/babel/babel

**Comment by dozoisch** [comment]
@thejameskyle Hey! Thanks a lot, actually I've already embraced Babel! 
- https://github.com/dozoisch/react-google-recaptcha
- https://github.com/dozoisch/react-async-script

Just that I haven't had time to migrate the code in this repo!

**Comment by thejameskyle** [comment]
Awesome!
