### ISSUE TITLE
Cannot GET /main.js

### ISSUE THREAD

**Issue by filmackay** [dozoisch/koa-react-full-example#22]
I get 404 on the /main.js when running this project untouched via `npm run hot-dev-server`. Thoughts on where to start?

So, it seems it is serving it up via `/_assets/main.js` but the file `dev-server-public/index.html` refers to it as `main.js` in the current directory?

**Comment by dozoisch** [comment]
Let me check that out, I rememer getting a similar error at some point

**Comment by dozoisch** [comment]
@filmackay Ok I think Ifound the issue, the port 2992 is only used by webpack for distributing assets.

You have to open 2 terminals one with `npm run hot-dev-server` and the other one with `npm start`. Then hit localhost:3000 in the browser! The file in dev-server-public must be a leftover from the refactor!

**Comment by dozoisch** [comment]
(whoop the issue got auto closed, feel free to close if it's resolved)

**Comment by filmackay** [comment]
Ok thanks - can you clarify how the http servers work know this example; it has confused me a bit thus far:

Eg.
3000: koa, root index, mongoose, controller back end
2992: express, webpack assets

??

**Comment by filmackay** [comment]
With this fix, my `http://localhost:3000/` returns:

```
Version - 0.4.2 #020bf93 - Changelog
```

**Comment by dozoisch** [comment]
The npm run hot-dev-server is really just the webpack dev-server which serves assets by modules and does the hot-reload 

Where npm start runs the koa app! In prod you'd run only the koa-app with the assets minified

**Comment by filmackay** [comment]
Yeah, the only confusing part is the wrapper for the front-end (index.html) comes from the back end. Convenient, I agree, but you could produce this front the front-end server / built files (?)

**Comment by dozoisch** [comment]
I guess that could be done, I'll try to look at it if I get some time!
