### ISSUE TITLE
Flux or a Flux-ish thingy

### ISSUE THREAD

**Issue by bhj** [dozoisch/koa-react-full-example#26]
Hi, just curious if you planned on adding [Reflux](https://github.com/spoike/refluxjs) or had feelings either way on a PR for it. The current implementation of the Auth store isn't too far off already. Thanks for this repo!

**Comment by dozoisch** [comment]
Hey! Yeah I was thinking about adding Reflux/Fluxxible or any other flux thingy! I'm just really out of time right now!

**Comment by bucaran** [comment]
Fluxxor may be the one to go with their Koa support.

**Comment by bhj** [comment]
[Flummox](https://github.com/acdlite/flummox) looks promising as well. Their [documentation/example](https://github.com/acdlite/flummox/tree/master/docs) is an isomorphic Koa app and it seems to share a lot of other dependencies too.

**Comment by dozoisch** [comment]
Im currently implementing fluxxor in my other project https://github.com/dozoisch/pointsgenie ... once I'm done an happy, I'll migrate the code here!

**Comment by dozoisch** [comment]
Flummox seems to be way better (since it's not using MIXINS and is way more es6) so I'll go flummox!

Might take a little bit of time before everything is implemented! But I look forward to it.

**Comment by bhj** [comment]
Cool! Just starting to switch from Reflux. Should be interesting.

**Comment by dozoisch** [comment]
Took me a while to get a starting example, but it's working, so I'm refactoring that other app, then refactoring this one! Be prepared for a big change hehe

**Comment by dozoisch** [comment]
https://github.com/rackt/react-router/pull/590

Once this is in, everything will be easier to do :/

**Comment by dozoisch** [comment]
https://github.com/acdlite/flummox/issues/170

And that too

**Comment by dozoisch** [comment]
If anyone is interested, I have a working example here : https://github.com/dozoisch/pointsgenie/pull/30

with server-side rendering. The only problem is that I had to use 2 forks for that.

**Comment by dozoisch** [comment]
see https://github.com/dozoisch/koa-react-full-example/tree/flummox

**Comment by tychotatitscheff** [comment]
What about marty.js for a flux implementation. Seems to handle isomorphic well and have nice es6 class.

**Comment by dozoisch** [comment]
@tychotatitscheff Looks nice also, but I don't really have the time right now :/. I have a WIP with flummox but haven't had any minute to complete it.

**Comment by tychotatitscheff** [comment]
@dozoisch I understand, was more for an exhaustif panel of the choice ! Nice example in between.

**Comment by dozoisch** [comment]
Incoming soon: Redux!

**Comment by bhj** [comment]
Redux looks awesome! Looking forward to it :smile:

**Comment by bhj** [comment]
Looks like 1.0 is out! http://rackt.github.io/redux/

**Comment by dozoisch** [comment]
@bhj yes I've seen that today! So awesome. Sorry for the delay... My colleague actually has a branch with the beginning of a redux migration in it... just haven't had time to finish it and merge it sadly

**Comment by bhj** [comment]
No worries, didn't want to duplicate effort. I'll probably give it a go anyway!
