### ISSUE TITLE
where is build/stats.json

### ISSUE THREAD

**Issue by xZGit** [dozoisch/koa-react-full-example#28]
as the title ,where is build/stats.json...

Error: Cannot find module '../../build/stats.json'

**Comment by dozoisch** [comment]
You have to build the project once at least before running server

whether `npm run hot-dev-server` or `npm run build`

**Comment by dozoisch** [comment]
@xZGit Has this fix your problem?

**Comment by xZGit** [comment]
yes！！！thank you very much！！！
