### ISSUE TITLE
No login page

### ISSUE THREAD

**Issue by mgleed** [dozoisch/koa-react-full-example#32]
Hey,

There's probably a simple solution to this, but I don't get a login page after following all of the instructions. Instead, I just get a line of text and a changelog link: "Version - 0.6.0 #1a22bb1 - Changelog." What am I doing wrong here? Didn't see any errors during the process of installing. I'm running nodejs v0.12.7, mongodb shell version is 3.0.4, npm version 2.11.3, on Debian 7.

Mitch

**Comment by dozoisch** [comment]
Any errors in whether the web console or one of the two terminals? Seems like a weird issue. What you see is part of the template that is server-side rendered

**Comment by mgleed** [comment]
No errors in either, but I imagine the error is still on my part. Any next steps to suggest? I'll redo the installation procedure in the meantime.

**Comment by dozoisch** [comment]
Check in the page, to see the url of the app.js. And try to access that directly. In hot server it should be something like localhost:2992...

**Comment by mgleed** [comment]
Yeah, that's right; and no, I can't access it ("//localhost:2992/_assets/app.js") from my PC. I'm running this all on a google compute virtual machine instance. Is it just that I'm not viewing the site from the server from which I'm running? I've been able to deploy other apps and frameworks.

**Comment by dozoisch** [comment]
Hum that's a good question! I don't think the webpack config is made for that right now... I'll try to look at it tonight!

**Comment by dozoisch** [comment]
@mgleed Can you try with v0.6.1? I've proxied webpack from koa, so it should be fine now!

**Comment by mgleed** [comment]
Unfortunately, with the new version, "npm run build && npm test" failed. Here is the npm log file:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@2.13.1
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild koa-react-full-example@0.6.1
7 info build koa-react-full-example@0.6.1
8 verbose unsafe-perm in lifecycle true
9 info koa-react-full-example@0.6.1 Failed to exec build script
10 verbose stack Error: koa-react-full-example@0.6.1 build: `NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors`
10 verbose stack spawn ENOENT
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid koa-react-full-example@0.6.1
12 verbose cwd /home/mitchellgleed_gmail_com/tvapp/koa-react-full-example
13 error Linux 3.16.0-0.bpo.4-amd64
14 error argv "node" "/usr/bin/npm" "run" "build"
15 error node v0.12.7
16 error npm  v2.13.1
17 error file sh
18 error code ELIFECYCLE
19 error errno ENOENT
20 error syscall spawn
21 error koa-react-full-example@0.6.1 build: `NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors`
21 error spawn ENOENT
22 error Failed at the koa-react-full-example@0.6.1 build script 'NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors'.
22 error This is most likely a problem with the koa-react-full-example package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors
22 error You can get their info via:
22 error     npm owner ls koa-react-full-example
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by dozoisch** [comment]
Can you delete node_modules and re-install? I'm in the dark right now, because test passed.

**Comment by mgleed** [comment]
I just did another fresh install and it seemed to work this time! Not sure what happened last round, sorry about that. The page is up and running, and I see the sign-in page as expected. 

Thanks!

**Comment by dozoisch** [comment]
Great :dancer:
