### ISSUE TITLE
FR: PostgreSQL?

### ISSUE THREAD

**Issue by bhj** [dozoisch/koa-react-full-example#33]
Just curious if you had any interest in PostgreSQL support. I was looking at using something like [postgres-gen](https://github.com/evs-chris/node-postgres-gen)

**Comment by dozoisch** [comment]
I looked it up for another project.

There was one lib that seemed very good:
- https://github.com/sequelize/sequelize

**Comment by bhj** [comment]
Knex looks cool and I like that it's not a full blown ORM but you can still scale from SQLite to Postgres. I wonder if something other than mongo might actually be easier for newbies (and use less terminals) but you probably want this repo to track the PG site closely. My data just always tends to end up SQL-y... :smile: I'll go ahead and close this; thanks for the links!
