### ISSUE TITLE
Trouble building on OSX 10.9

### ISSUE THREAD

**Issue by richb-hanover** [dozoisch/koa-react-full-example#35]
I ran into a couple problems building the current (174015cc6b)  koa-react-full-example on OSX 10.9. I started by git clone from the github repo, then ran these commands:

`npm install` got several errors:  http://pastebin.com/awweJkQf

`npm run build && npm test` got different errors: http://pastebin.com/GvCYrHs1

Any thoughts for resolving this? Should I wait 'til my new 10.10 machine comes in next week? Thanks!

Update: There was no npm-debug.log file generated...

**Comment by richb-hanover** [comment]
Update and Solution: I solved my own (two) problems...

**Problem 1)** I was using iojs, not node. I had recently installed iojs, and got its own version of npm.  I'm not sure what the difference is, but here is the config output:

```
# Using current iojs
bash-3.2$ npm config list
; cli configs
user-agent = "npm/2.13.3 node/v3.2.0 darwin x64"

; node bin location = /usr/local/bin/iojs
; cwd = /Users/richb
; HOME = /Users/richb
; 'npm config ls -l' to show all defaults.
bash-3.2$
```

vs 

```
# Using node 0.12.7
bash-3.2$ npm config list
; cli configs
user-agent = "npm/2.11.3 node/v0.12.7 darwin x64"

; node bin location = /usr/local/bin/node
; cwd = /Users/richb/github/kaliweb
; HOME = /Users/richb
; 'npm config ls -l' to show all defaults.
bash-3.2$
```

**Problem 2)** Running `npm install` worked with a flaw. But the build/test step threw errors containing 'MongoError: ..." The fix was to start mongo by issuing this command in another window: `mongod --config /usr/local/etc/mongod.conf`

**Comment by dozoisch** [comment]
Yeah with iojs, it seems like latest release have broken the build. I'll try to check it out as soon as I can.

And indeed first error was caused by mongo not running. I need to add that to the readme!

Thank you!

**Comment by 3vand0ng** [comment]
Hi dozoisch, 
I am building on OSX 10.11 have a wrong.

this is log 
95% emitfatal: Not a git repository (or any of the parent directories): .git
child_process.js:484
    throw err;
    ^

Error: Command failed: git rev-parse --short HEAD
fatal: Not a git repository (or any of the parent directories): .git

```
at checkExecSyncError (child_process.js:441:13)
at execSync (child_process.js:481:13)
at Compiler.<anonymous> (/Users/xxxx/Sites/koa-react-full-example-master/webpack/strategies/version.js:17:31)
at Compiler.applyPlugins (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
at Compiler.<anonymous> (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:193:12)
at Compiler.emitRecords (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:282:37)
at Compiler.<anonymous> (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:187:11)
at /Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:275:11
at Compiler.applyPluginsAsync (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
at Compiler.afterEmit (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:272:8)
at Compiler.<anonymous> (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/lib/Compiler.js:267:14)
at /Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /Users/xxxx/Sites/koa-react-full-example-master/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:42:10
at FSReqWrap.oncomplete (fs.js:82:15)
```

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! koa-react-full-example@0.6.1 build: `NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the koa-react-full-example@0.6.1 build script 'NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors'.
npm ERR! This is most likely a problem with the koa-react-full-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --config webpack.config.js --separate-stylesheet -p --progress --profile --colors
npm ERR! You can get their info via:
npm ERR!     npm owner ls koa-react-full-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/Sites/koa-react-full-example-master/npm-debug.log

**Comment by dozoisch** [comment]
That's because the package expected to be in a git repo.
